// 危险作业安全措施模板（基于 GB 30871-2022 + 企业规程）
const SAFETY_MEASURES: Record<string, Array<{ category: string; content: string; note?: string; sort: number }>> = {
  hot_work: [
    { category: 'pre', content: '氧气乙炔气瓶间距≥5m，离明火≥10m', sort: 1 },
    { category: 'pre', content: '周边易燃物可燃物清除干净，无法移除的采取有效隔离措施', sort: 2 },
    { category: 'pre', content: '检查周围有无油漆等交叉作业，有则避免同时或有效隔离', sort: 3 },
    { category: 'pre', content: '危险作业（焊接）持有效操作证，复印件提交审批', sort: 4 },
    { category: 'pre', content: '配置有效灭火器', sort: 5 },
    { category: 'pre', content: '盛过化学品的容器、设备、管道须清洗置换且分析合格', sort: 6 },
    { category: 'pre', content: '高处动火须检查下方可燃物、空洞、阴井等并采取隔火措施', sort: 7 },
    { category: 'pre', content: '电、气焊工具安全可靠，不带病使用', sort: 8 },
    { category: 'pre', content: '安全事项已向动火人员告知', sort: 9 },
    { category: 'pre', content: '指定监火人（必须）', sort: 10, note: '填写监火人姓名' },
    { category: 'during', content: '搬运气瓶须用专用台车', sort: 11 },
    { category: 'during', content: '发现不明化学品搬运经过应暂停作业', sort: 12 },
    { category: 'after', content: '动火后检查现场，确认无残留火种，清理恢复', sort: 13 },
  ],
  high_altitude: [
    { category: 'pre', content: '作业人员持有效高空悬挂作业证', sort: 1, note: '提供证书编号' },
    { category: 'pre', content: '安全帽、安全绳、工具袋、通信设备齐全', sort: 2 },
    { category: 'pre', content: '拆除或加以固定施工区域周围可能坠落的物体', sort: 3 },
    { category: 'pre', content: '脚手架、防护围栏符合安全规程', sort: 4 },
    { category: 'pre', content: '梯子、绳梯符合安全规程', sort: 5 },
    { category: 'pre', content: '物料摆放平稳，拆件及时清走', sort: 6 },
    { category: 'pre', content: '雨雪天气禁止室外高空作业', sort: 7 },
    { category: 'pre', content: '移动梯梯脚坚实，不垫高使用', sort: 8 },
    { category: 'pre', content: '立梯角度70°~80°，踏板间距30cm以内，无缺档', sort: 9 },
    { category: 'pre', content: '梯子接长后接头不超过1处', sort: 10 },
    { category: 'pre', content: '折梯上部夹角35°~45°，铰链牢固，有可靠拉撑', sort: 11 },
    { category: 'pre', content: '指定监护人（必须）', sort: 12, note: '填写监护人姓名' },
  ],
  temporary_electricity: [
    { category: 'pre', content: '临时线路安装人员持危险作业人员电工操作证', sort: 1 },
    { category: 'pre', content: '防爆场所的临时电源、电气元件达到相应防爆等级', sort: 2 },
    { category: 'pre', content: '单相和混用线路采用五线制', sort: 3 },
    { category: 'pre', content: '线路架空高度：装置内≥2.5m，道路≥5m', sort: 4 },
    { category: 'pre', content: '架空线不用裸线，不在树上或脚手架上架设', sort: 5 },
    { category: 'pre', content: '配电盘/箱有防雨措施', sort: 6 },
    { category: 'pre', content: '漏电保护器有效，手持工具一机一闸一保护', sort: 7 },
    { category: 'pre', content: '用电设备、线路容量和负荷符合要求', sort: 8 },
  ],
  lifting: [
    { category: 'pre', content: '作业前安全教育已完成', sort: 1 },
    { category: 'pre', content: '指挥人员及起重工持有效危险作业人员操作证', sort: 2, note: '填写证书编号' },
    { category: 'pre', content: '≥40T或复杂/精密/贵重吊装须编制作业方案且经主管部门及安全管理部门审批', sort: 3 },
    { category: 'pre', content: '指定专人监护并坚守岗位，禁止非作业人员入内', sort: 4 },
    { category: 'pre', content: '吊装区域设警戒线，无关人员禁止进入', sort: 5 },
    { category: 'pre', content: '吊索具、吊钩、钢丝绳等检查合格', sort: 6 },
    { category: 'pre', content: '严禁超载吊装', sort: 7 },
    { category: 'pre', content: '指挥信号明确统一，通信畅通', sort: 8 },
    { category: 'pre', content: '风力≥6级（10.8m/s）禁止露天吊装', sort: 9 },
    { category: 'during', content: '吊臂下严禁站人', sort: 10 },
    { category: 'after', content: '吊装完毕，设备归位，场地清理', sort: 11 },
  ],
  excavation: [
    { category: 'pre', content: '地下管线、电缆等已勘查确认位置并标识', sort: 1 },
    { category: 'pre', content: '深度≥1.5m 须放坡或加支撑，防止塌方', sort: 2 },
    { category: 'pre', content: '作业区域设警示标志和围栏，夜间红灯警示', sort: 3 },
    { category: 'pre', content: '坑深≥2m 须设人员上下通道', sort: 4 },
    { category: 'pre', content: '土方堆放距坑边≥1m，高度≤1.5m', sort: 5 },
    { category: 'pre', content: '机械作业���定专人统一指挥', sort: 6 },
    { category: 'pre', content: '有排水措施，雨后须检查确认安全', sort: 7 },
    { category: 'during', content: '作业中应持续观察坑壁稳定情况', sort: 8 },
    { category: 'after', content: '作业完毕及时回填，拆除围栏恢复通行', sort: 9 },
  ],
  confined_space: [
    { category: 'pre', content: '作业前须进行气体检测（氧含量、可燃气体、有毒气体）并记录数据', sort: 1, note: '填写检测数据' },
    { category: 'pre', content: '采取有效通风措施（自然通风或强制机械通风）', sort: 2 },
    { category: 'pre', content: '作业人员配备个人防护用品（防毒面具/空气呼吸器/安全绳等）', sort: 3 },
    { category: 'pre', content: '外部设专职监护人，保持可靠通信', sort: 4, note: '填写监护人姓名及联系方式' },
    { category: 'pre', content: '制定应急救援方案，配备救援器材（三脚架/救援绳等）', sort: 5 },
    { category: 'pre', content: '照明采用≤12V安全电压，电气设备防爆', sort: 6 },
    { category: 'pre', content: '与受限空间连通的可能危及安全的管道/孔洞采取隔离（盲板/断开）', sort: 7 },
    { category: 'pre', content: '进出须登记签名，作业中持续气体监测', sort: 8 },
    { category: 'during', content: '监护人不得离岗，每2h重新气体检测并记录', sort: 9 },
    { category: 'after', content: '作业完毕清点人员工具，关闭入口', sort: 10 },
  ],
  blind: [
    { category: 'pre', content: '盲板材质、规格须符合设计要求', sort: 1, note: '填写盲板规格' },
    { category: 'pre', content: '管线须泄压、排空、吹扫置换合格后加装盲板', sort: 2 },
    { category: 'pre', content: '盲板抽堵作业前须确认隔离点准确无误', sort: 3 },
    { category: 'pre', content: '盲板须编号挂牌管理', sort: 4 },
    { category: 'pre', content: '防静电措施到位（接地、工具为有色金属）', sort: 5 },
    { category: 'after', content: '作业完毕确认盲板位置和数量，建立盲板图台账', sort: 6 },
  ],
  other: [
    { category: 'pre', content: '作业前进行安全风险评估（JSA），明确危险源和控制措施', sort: 1 },
    { category: 'pre', content: '作业人员已接受专项安全技术交底', sort: 2 },
    { category: 'pre', content: '个人防护装备（PPE）按要求配备齐全', sort: 3 },
    { category: 'pre', content: '指定现场负责人和安全监护人', sort: 4 },
    { category: 'pre', content: '应急措施和逃生通道已确认', sort: 5 },
  ],
};
export default SAFETY_MEASURES;
